version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: todo-backend:latest
    restart: always
    environment:
      - DB_URL=sqlite:////data/todo.db
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGINS=["${FRONTEND_URL}"]
      - LOG_LEVEL=INFO
    volumes:
      - backend_data:/data
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  backend_data:
    driver: local